import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Transcript Sandbox</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Transcript <span className="text-[hsl(280,100%,70%)]">Sandbox</span>
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/chat"
            >
              <h3 className="text-2xl font-bold">Chat →</h3>
              <div className="text-lg">
                A page demonstrating live chat and message dictation
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/meeting"
            >
              <h3 className="text-2xl font-bold">Meeting →</h3>
              <div className="text-lg">
                A page demonstrating a Whereby video call with live voice
                transcription
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
